FROM node:latest
MAINTAINER Andrew Phillips <theasp@gmail.com>

WORKDIR /tmp
ENV CLOJURE_VER=1.10.1.492

RUN apt-get update \
  && apt-get -q -y install openjdk-8-jdk curl \
  && npm install -g shadow-cljs \
  && curl -s https://download.clojure.org/install/linux-install-$CLOJURE_VER.sh | bash

# Install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -y google-chrome-stable
